- name: Install System Packages 1
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev", "xz-utils"]

- name: Install System Packages 2
  become: true
  apt:
    name: ["lua5.4", "clang", "unzip", "libtool", "libtool-bin", "gettext", "ccache", "ninja-build", "curl"]

- name: Install tools
  become: true
  apt:
    name: ["fzf", "tmux", "stow"]

- name: Install deb tools
  become: true
  apt:
    deb: "{{ item }}"
  loop:
    - https://github.com/BurntSushi/ripgrep/releases/download/14.0.3/ripgrep_14.0.3-1_amd64.deb
    - https://github.com/sharkdp/fd/releases/download/v9.0.0/fd_9.0.0_amd64.deb
