- name: Install ZSH
  become: true
  apt: name=zsh

- name: debug
  become: true
  debug:
    var: ansible_user_id

- name: Change shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Install Oh-My-Zsh
  block:
    - name: Check that the Oh-My-Zsh installed
      stat:
        path: ~/.oh-my-zsh
      register: oh_my_stats

    - name: Oh-My-Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not oh_my_stats.stat.exists

    - name: Install zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"

    - name: Install zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
  when: zsh_prompt == 'oh-my-zsh'

- name: Install Starship
  block:
    - name: Check Starship installed
      stat:
        path: /usr/local/bin/starship
      register: star_stat

    - name: Starship
      shell: curl -sS https://starship.rs/install.sh | sh
      when: not star_stat.stat.exists
  when: zsh_prompt == 'starship'
