- hosts: localhost
  vars:
    neovim_version: v0.9.5
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - import_tasks: ../tasks/core-setup.yml
    - import_tasks: ../tasks/nvim-setup.yml
      tags:
        - install
        - neovim
