- hosts: localhost
  vars:
    neovim_version: v0.9.5
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        update_cache: true
        state: present
  tasks:
    - import_tasks: ../tasks/core.yml
      tags: core
    - import_tasks: ../tasks/nvim.yml
      tags: nvim
    - import_tasks: ../tasks/tmux.yml
      tags: tmux
    - import_tasks: ../tasks/zsh.yml
      tags: zsh
    - import_tasks: ../tasks/dotfiles.yml
      tags: dotfiles
